server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /preview {
    return 301 /preview/;
  }

  location ^~ /preview/ {
    rewrite ^/preview/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
